version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env # Carrega as variáveis de ambiente do arquivo .env local
    ports:
      - "5000:5000" # Exemplo de mapeamento de porta, ajuste conforme necessário
